Feat/civ 1616 send notification noc
hmcts/civil-service pull request #1357
Opened 2022-08-22 15:48 UTC by kurt-uk

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-1616

### Change description ###
Added callback handler for NOC former and other sol 1 and 2, will skip former sol if the case has LiP as there is no former sol to contact. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-08-30 08:54 UTC, HarryH96 submitted a review, later dismissed

2022-08-30 09:19 UTC, sherlynkhaw requested changes

2022-08-30 09:19 UTC, sherlynkhaw commented on src/main/java/uk/gov/hmcts/reform/civil/utils/NocNotificationUtils.java
> +        if (isRespondent2NewSolicitor(caseData)) {
why is it that only when Respondent2 Solicitor is changed, we notify applicantsolicitor?

Shouldn't all be applicantsolicitor?

2022-08-30 09:19 UTC, sherlynkhaw commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ChangeOfRepresentationNotificationHandlerTest.java
> +            void shouldNotifyFormerSolicitorWhenInvoked_whenInvoked() {
remove double when invoked?

2022-08-30 14:49 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/civil/utils/NocNotificationUtils.java
> +            otherSolicitor1Email = caseData.getRespondentSolicitor2EmailAddress();
we only get respondent 2 if the event is triggered for that 2nd solicitor

2022-08-30 14:49 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/civil/utils/NocNotificationUtils.java
> +        } else {
not sure what you mean, the logic for the scenarios were dicussed and that didnt come up

2022-08-30 14:51 UTC, kurt-uk commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/ChangeOfRepresentationNotificationHandlerTest.java
> +            void shouldNotifyFormerSolicitorWhenInvoked_whenInvoked() {
done

2022-09-05 08:25 UTC, sherlynkhaw submitted a review, later dismissed
I think it looks better now!
I would add some comments in your NocNotificationUtils.java, so it'll be easier to read/digest later on.

2022-09-05 08:25 UTC, sherlynkhaw commented on src/main/java/uk/gov/hmcts/reform/civil/utils/NocNotificationUtils.java
> +                return RecipientData.builder()
hmmm, if it's a 2v1, do we need to notify applicantsolicitor1 again? i think it's worth a check with BAs/Leanne

2022-12-08 10:58 UTC, sankaviv1 approved these changes

2022-12-16 09:58 UTC, LTurkingtonHMCTS submitted a review, later dismissed

2023-01-31 12:56 UTC, Gareth40343 approved these changes

2023-01-31 14:01 UTC, HarryH96 approved these changes

2023-01-31 14:01 UTC, LTurkingtonHMCTS approved these changes

2023-01-31 14:11 UTC, merged