feat/CIV-4674, made the changes to remove deadline
hmcts/civil-service pull request #1466
Opened 2022-09-22 10:51 UTC by indu2019

Remove Deadline to respond when defendant is not represented after Claim has been issued

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/CIV-4674

Change description
Remove Deadline to respond when defendant is not represented after Claim has been issued

Does this PR introduce a breaking change? (check one with "x")

[ ] Yes
[x ] No

2022-10-03 10:23 UTC, indu2019 commented
Closing it for now

2022-10-03 10:24 UTC, indu2019 commented
Reopening it

2022-10-05 12:32 UTC, asthamalviya approved these changes

2022-10-07 08:25 UTC, maciejmodzelewski requested changes
This PR has a conflict that has to be resolved
![image](https://user-images.githubusercontent.com/18092228/194508145-bb3b2fc8-46c5-46c0-bd3e-3bab61624645.png)

2022-10-07 10:18 UTC, sabahirfan approved these changes

2022-10-07 11:16 UTC, kamilewandowski approved these changes

2022-10-07 11:23 UTC, maciejmodzelewski approved these changes

2022-10-07 11:24 UTC, merged