CIV-3914: Access Profile Changes
hmcts/civil-service pull request #1501
Opened 2022-09-28 15:54 UTC by Azam-Hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-3914

### Change description ###
 we are utilising Access Profiles which rely upon fields being configured in case data called: CaseAccessCategory
Currently within the legal representative journeys, we populate a case field called SuperClaimType which is set to: SPEC_CLAIM or UNSPEC_CLAIM depending on the Case Event that initiated the application - we need to migrate values in production cases from: 
SuperClaimType into a new Case Access Category field.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-09-29 11:26 UTC, douglasrice requested changes

2022-09-29 11:26 UTC, douglasrice commented on config/owasp/suppressions.xml
> +    <cve>CVE-2022-38752</cve>
Please remove this suppression - a fix has been deployed to master

2022-09-29 16:13 UTC, vasudevganesanhmcts commented on config/owasp/suppressions.xml
> +    <cve>CVE-2022-38752</cve>
added it temporarily to get pipelines moving . .have removed it thanks

2022-09-30 07:18 UTC, vasudevganesanhmcts approved these changes

2022-09-30 08:53 UTC, MMNycz approved these changes

2022-09-30 09:29 UTC, douglasrice approved these changes

2022-09-30 12:27 UTC, vasudevganesanhmcts approved these changes

2022-09-30 12:29 UTC, MMNycz approved these changes

2022-09-30 13:16 UTC, merged