CIV-4673 Change Deadline to respond logic from 14 days to 28 days
hmcts/civil-service pull request #1542
Opened 2022-10-05 16:06 UTC by indu2019

Change Deadline to respond logic from 14 days to 28 days 

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-4673

### Change description ###
Change Deadline to respond logic from 14 days to 28 days 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-10-06 09:04 UTC, sabahirfan submitted a review, later dismissed
LGTM

2022-10-06 10:37 UTC, maciejmodzelewski commented on config/owasp/suppressions.xml
> +    <cve>CVE-2022-42004</cve>
CVE-2022-42004 can be fixed by updating jackson-databind to version 2.13.4.

2022-10-07 08:06 UTC, kamilewandowski requested changes

2022-10-07 08:59 UTC, asthamalviya approved these changes

2022-10-07 11:34 UTC, kamilewandowski approved these changes

2022-10-10 10:45 UTC, asthamalviya submitted a review, later dismissed

2022-10-10 16:24 UTC, indu2019 commented
closing it

2022-10-10 16:25 UTC, indu2019 commented
closing it

2022-10-10 16:27 UTC, indu2019 commented
opening it

2022-10-11 11:37 UTC, asthamalviya approved these changes

2022-10-11 11:40 UTC, jeejavr approved these changes

2022-10-11 12:08 UTC, sabahirfan approved these changes

2022-10-12 16:33 UTC, merged