Feat/civ 4956 evidence upload event
hmcts/civil-service pull request #1658
Opened 2022-10-21 17:28 UTC by drummondjm

https://tools.hmcts.net/jira/browse/CIV-4956

evidence upload event and tests.
Does this PR introduce a breaking change? (check one with "x")

```
[ ] Yes
[ x] No
```

2022-10-24 09:55 UTC, hmcts-version1-ignacio approved these changes

2022-10-24 12:16 UTC, filippo-possenti-version1 commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/EvidenceUploadHandlerTest.java
> +        }
What's being tested here?

I don't see any assertion or anyway anything that could give a clue as to when the test is succeeding or failing.

Same for the other tests in this class.

Please clarify in the code what defines the test as successful. If assertions don't apply, put an inline comment of sorts.

2022-10-24 12:18 UTC, filippo-possenti-version1 requested changes
Try to clarify when the test is succeeding or failing in some way.

Get in touch with me if you struggle to find an effective way to convey this in those tests or if you feel there's a specific reason why those tests should stay that way.

2022-10-25 06:59 UTC, hmcts-version1-ignacio approved these changes

2022-10-25 10:34 UTC, m-meulendijks-v1 approved these changes

2022-10-25 14:07 UTC, filippo-possenti-version1 approved these changes

2022-10-25 16:47 UTC, merged