updated template and added fields in DJ order form and generator under toggle
hmcts/civil-service pull request #1685
Opened 2022-10-28 15:03 UTC by kurt-uk

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-4705

### Change description ###
updated docmosis template and document generator, courtLocation field is populated by caseManagementLocation under a feature toggle, and added order made without hearing field for form

## Docmosis screenshots
![Screenshot 2022-10-28 at 16 02 11](https://user-images.githubusercontent.com/26488566/198665779-29a3eaad-9700-4cef-956a-139ba80a9542.png)

![Screenshot 2022-10-28 at 16 02 31](https://user-images.githubusercontent.com/26488566/198666064-b921238a-a31b-4101-8bac-76049a23dbb1.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-31 10:17 UTC, HarryH96 approved these changes

2022-10-31 10:21 UTC, sankaviv1 submitted a review, later dismissed

2022-10-31 10:34 UTC, HarryH96 requested changes
Can we split out the changes on this template. SDO / DJ may still go before HNL is merged. Therefore we dont want to make any changes to their templates

2022-11-01 10:16 UTC, LTurkingtonHMCTS submitted a review, later dismissed

2022-11-03 13:46 UTC, sankaviv1 approved these changes

2022-11-03 15:47 UTC, sherlynkhaw approved these changes

2022-11-11 10:54 UTC, asthamalviya approved these changes

2022-11-11 10:56 UTC, sankaviv1 submitted a review, later dismissed

2022-11-16 14:03 UTC, HarryH96 approved these changes

2022-11-28 12:07 UTC, alberto-hortiguela approved these changes

2022-11-28 12:17 UTC, merged