Civ 6055
hmcts/civil-service pull request #2072
Opened 2023-01-09 12:13 UTC by hgulv1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-6055

### Change description ###
Setting a more descriptive error message for a nullpointer exception occuring when responding to a claim

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-01-09 16:41 UTC, darrenHMCTS submitted a review, later dismissed

2023-01-10 11:12 UTC, jeejavr requested changes

2023-01-10 11:14 UTC, asthamalviya requested changes
I wonder how primary address missing is a BAD_REQUEST error?

2023-01-10 14:21 UTC, hgulv1 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
> +
spoke offline and agreed on changes

2023-01-10 14:21 UTC, hgulv1 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
> +            throw new HttpClientErrorException(HttpStatus.BAD_REQUEST, "Primary Address cannot be empty");
new changes will solve this

2023-01-10 14:37 UTC, asthamalviya requested changes
In this case the code will simply not run if information is missing. While we need is throw a proper error in case we come across to null pointer exception.

2023-01-11 10:53 UTC, asthamalviya approved these changes

2023-01-11 11:21 UTC, jeejavr approved these changes

2023-01-12 11:08 UTC, merged