CIV-6333, claimant select immediately
hmcts/civil-service pull request #2082
Opened 2023-01-10 22:03 UTC by indu2019

Email update sent to Claimant if defendant admits all and agrees to pay immediately

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-6333

### Change description ###
Email update sent to Claimant if defendant admits all and agrees to pay immediately

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-01-12 10:50 UTC, sabahirfan commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantResponseApplicantNotificationHandler.java
> +            if (caseData.getDefenceAdmitPartPaymentTimeRouteRequired().equals(IMMEDIATELY)) {
```suggestion
            if (caseData.getDefenceAdmitPartPaymentTimeRouteRequired() == IMMEDIATELY) {
```

2023-01-12 10:51 UTC, sabahirfan commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/DefendantResponseApplicantNotificationHandler.java
> +            if (caseData.getDefenceAdmitPartPaymentTimeRouteRequired().equals(IMMEDIATELY)) {
```suggestion
            if (caseData.getDefenceAdmitPartPaymentTimeRouteRequired() == IMMEDIATELY) {
```

2023-01-12 10:54 UTC, sabahirfan commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimSpecCallbackHandler.java
> +            &&  caseData.getDefenceAdmitPartPaymentTimeRouteRequired().equals(IMMEDIATELY)) {
```suggestion
            &&  caseData.getDefenceAdmitPartPaymentTimeRouteRequired() == IMMEDIATELY) {
```

Double Equal Sign (“==”) is null-safe whereas the equals() method is not. The equals() is a method of Enum class. If we try to call that method on a NULL reference we get a NullPointerException . 

“==” provides null-safety and type-safety during compile-time.

2023-01-12 13:45 UTC, sabahirfan submitted a review, later dismissed

2023-01-25 16:12 UTC, jeejavr approved these changes

2023-01-25 16:15 UTC, jeejavr requested changes
shouldNotifyApplicantSolicitorSpecImmediately_whenInvoked() seems to be failing

2023-01-27 10:19 UTC, closed without merging