fix: RPA 35 character address line fix (CMC-1708)
hmcts/civil-service pull request #218
Opened 2021-08-04 13:23 UTC by adamjhc

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CMC-1708

### Change description ###

See ticket for implementation details. Attempts to wrap the last comma-separated value in an address line around to the next one if the line exceeds 35 characters in length.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-08-09 10:44 UTC, ckalista requested changes
Hey Adam, I think the code can be simplified a lot if we take a new direction. Let's review that together. Chris

2021-08-09 10:44 UTC, ckalista commented on src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsAddressMapper.java
> +        String[] addressSplit = addressLines[addressLineIndex].split(", ");
The split should be exclusively on the comma. The space here will result in missed opportunities to fix addresses.

2021-08-09 10:44 UTC, ckalista commented on src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsAddressMapper.java
> +        String[] addressSplit = addressLines[addressLineIndex].split(", ");
Could we try to make use of regular expressions instead? `'/(.*),/'`

This would yield to safe and more readable code.

2021-08-09 10:44 UTC, ckalista commented on src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsAddressMapper.java
> +        if (addressLines[addressLineIndex + 1] == null) {
Could we also try to make use of collections (ArrayList) instead of manipulating arrays and indexes?

2021-08-09 10:44 UTC, ckalista commented on src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsAddressMapper.java
> +                return toNonDefaultRoboticsAddress(alteredAddress);
Hey, do we a `toNonDefaultRoboticsAddress` and a `toDefaultRoboticsAddress`? I am not sure I understand the reason why it's there...

2021-08-09 10:44 UTC, ckalista commented on src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsAddressMapper.java
> +        if (addressLines[0].length() > 35) {
If there a null check missing here?

2021-08-09 10:44 UTC, ckalista commented on src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/RoboticsAddressMapper.java
> +        if (addressLines[addressLineIndex + 1] == null) {
As a bonus, one could re-write this recursively ;-)

2021-08-23 10:36 UTC, adamjhc commented
closing in favour of #223

2021-08-23 10:36 UTC, closed without merging