CIV-6955 Remove PBA data collection
hmcts/civil-service pull request #2261
Opened 2023-02-09 11:02 UTC by miguelMolina3691

**Before creating a pull request make sure that:**

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-6955

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-02-14 15:45 UTC, m-meulendijks-v1 approved these changes

2023-02-14 15:46 UTC, hmcts-version1-ignacio approved these changes

2023-02-15 09:33 UTC, filippo-possenti-version1 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/ServiceRequestAPIHandler.java
> +                                                  .fee(fee)
I suspect this bit needs to be behind feature flag.

Can you please check?

2023-02-15 09:33 UTC, filippo-possenti-version1 requested changes
I believe there's a bit that needs to be behind feature flag.

2023-02-15 09:38 UTC, filippo-possenti-version1 commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/ServiceRequestAPIHandlerTest.java
> +        void shouldMakeHearingPaymentServiceRequest_whenInvoked() throws Exception {
Same as above. Given/When/Then comments.

2023-02-15 09:49 UTC, filippo-possenti-version1 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/ServiceRequestAPIHandler.java
> +                                                  .fee(fee)
Nevermind.

2023-03-07 10:29 UTC, filippo-possenti-version1 submitted a review, later dismissed

2023-03-07 11:07 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-03-08 17:03 UTC, filippo-possenti-version1 commented
This was green yesterday. Today it's not due to an unrelated issue with dates and bank holidays.
Approvals got removed due to a merge conflict but it's really all good.

I'll be overriding protections and merge this, knowing that the builds will turn red due to the unrelated issue.

2023-03-08 17:04 UTC, filippo-possenti-version1 approved these changes

2023-03-08 17:04 UTC, merged