CIV 6915
hmcts/civil-service pull request #2330
Opened 2023-02-23 09:56 UTC by suvarnathekkoot

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-6915

### Change description ###

Refactor respondent notifications in Hearing Notice

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-02-23 10:52 UTC, drummondjm submitted a review, later dismissed

2023-02-24 17:16 UTC, filippo-possenti-version1 commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationDefendantOfHearingHandlerTest.java
> +                "NOTIFY_DEFENDANT_HEARING").build()).build())).isEqualTo(TASK_ID_DEFENDANT1);
This unit test fails.

NOTIFY_DEFENDANT_HEARING should be NOTIFY_DEFENDANT1_HEARING.

2023-02-24 17:17 UTC, filippo-possenti-version1 requested changes
The unit-test is broken

2023-03-07 14:34 UTC, filippo-possenti-version1 submitted a review, later dismissed

2023-04-03 08:14 UTC, drummondjm approved these changes

2023-04-03 11:17 UTC, drummondjm submitted a review, later dismissed

2023-04-03 13:44 UTC, kurt-uk submitted a review, later dismissed

2023-04-24 08:46 UTC, miguelMolina3691 submitted a review, later dismissed

2023-04-24 10:16 UTC, sankhajuria approved these changes

2023-04-24 12:23 UTC, miguelMolina3691 approved these changes

2023-04-24 12:26 UTC, drummondjm approved these changes

2023-04-24 12:32 UTC, merged