CIV-7410 update unit tests, should be 100% method coverage now
hmcts/civil-service pull request #2353
Opened 2023-02-28 16:10 UTC by drummondjm

https://tools.hmcts.net/jira/browse/CIV-7410

Unit test updates to increase coverage 
GenerateDJFormHandler
AssignCaseToUserHandler
 
**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-02-28 16:35 UTC, m-meulendijks-v1 approved these changes

2023-02-28 17:08 UTC, filippo-possenti-version1 requested changes
See comments.

Also, the AssignCaseToUserHandler class has an if statement on line 89. For that test I would like you to make it explicit everywhere whether we are assuming toggleService.isGlobalSearchEnabled() to return true or false and add the missing tests where it's clear that we're missing either one or the other.
This way we will ensure that the methods behave as intended for the various permutations.

2023-02-28 17:08 UTC, filippo-possenti-version1 commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToUserHandlerTest.java
> +    }
Add a test similar to these ones that captures the exception being thrown on line 70 of AssigneCaseToUserHandler, so we get to 100% line coverage.

2023-02-28 17:08 UTC, filippo-possenti-version1 commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToUserHandlerTest.java
> +                                                                     ASSIGN_CASE_TO_APPLICANT_SOLICITOR1_SPEC);
Make it an exact match, so if people adds new events they are forced to look at the tests.

2023-02-28 17:19 UTC, filippo-possenti-version1 commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateDJFormHandlerTest.java
> +    }
Same as above

2023-02-28 17:22 UTC, filippo-possenti-version1 commented
Also, take the opportunity to resolve the many SonarLint warnings that this test class has.

Not strictly part of the Acceptance Criteria, but it would be a welcome improvement.

2023-03-01 15:35 UTC, filippo-possenti-version1 commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToUserHandlerTest.java
> +    }
Done in @ParameterizedTest. Resolving conversation.

2023-03-02 11:57 UTC, filippo-possenti-version1 approved these changes

2023-03-02 12:00 UTC, m-meulendijks-v1 approved these changes

2023-03-02 12:58 UTC, filippo-possenti-version1 commented
The build turned red on functional tests. However this PR doesn't change the code: all it does is adding unit-tests. As a result the issues on the build are separate and the build failure is unrelated to this PR.

The conditions for this PR to be "mergeable" are actually that the new unit-tests are passing and that there are the necessary approvals.

As both the above conditions are satisfied, I'll be overriding branch protections and merge this PR.

2023-03-02 12:59 UTC, merged