CIV-7788 Hearing fee look up
hmcts/civil-service pull request #2518
Opened 2023-03-24 13:52 UTC by miguelMolina3691

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-7788

### Change description ###
Look up hearing fee

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-03-27 16:49 UTC, filippo-possenti-version1 requested changes
Some improvements can be made to the code quality.

Once you get to it, if you apply my suggestions make sure to run the build locally as I expect at least one checkstyle exception and one compile exception due to imports.

2023-03-27 16:49 UTC, filippo-possenti-version1 commented on src/test/java/uk/gov/hmcts/reform/civil/service/hearings/HearingFeesServiceTest.java
> +            RestClientException.class, () -> feesService.getFeeForHearingSmallClaims(claimAmount));
The following is needed if you apply other suggestions.

```suggestion
            InternalServerErrorException.class, () -> feesService.getFeeForHearingSmallClaims(claimAmount));
```

2023-03-28 07:04 UTC, miguelMolina3691 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledHandler.java
> +        }
Modified

2023-03-28 07:06 UTC, miguelMolina3691 commented on src/main/java/uk/gov/hmcts/reform/civil/service/hearings/HearingFeesService.java
> +    }
This is due to the fees registry. There is a jurisdiction field and a jurisdiction2 field, which for some fees is different

2023-03-30 11:25 UTC, merged