CIV-6293 orders journey assisted order
hmcts/civil-service pull request #2526
Opened 2023-03-28 08:46 UTC by miguelMolina3691

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-03-29 08:26 UTC, drummondjm submitted a review, later dismissed

2023-03-31 09:31 UTC, kurt-uk requested changes

2023-03-31 11:26 UTC, miguelMolina3691 commented on src/main/java/uk/gov/hmcts/reform/civil/enums/finalorders/HearingMethodFinalOrderList.java
> +public enum HearingMethodFinalOrderList {
I wanted to separate them because they belong to different events, but yes, in the end they are the same. I modify it

2023-04-03 11:19 UTC, drummondjm approved these changes

2023-04-03 14:14 UTC, kurt-uk approved these changes

2023-04-04 09:47 UTC, bhagyashreesharma90 approved these changes

2023-04-25 11:10 UTC, merged