Feat/civ 7646
hmcts/civil-service pull request #2551
Opened 2023-04-04 08:50 UTC by bhagyashreesharma90

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-7646

### Change description ###
Added bundle trigger api in testing controller

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-04-06 09:34 UTC, filippo-possenti-version1 commented on Jenkinsfile_CNP
> -def ccdBranch = "master"
Marking as "request changes" to ensure this doesn't get merged by mistake.

2023-04-06 09:34 UTC, filippo-possenti-version1 requested changes
All good from my perspective.

Marking as "request changes" to prevent merging the Jenkinsfile_CNP change by mistake.

2023-04-06 12:47 UTC, mounikahmcts approved these changes

2023-04-07 10:26 UTC, filippo-possenti-version1 approved these changes

2023-04-07 10:56 UTC, filippo-possenti-version1 commented
There's nobody around today for the second approval, but this was actually cleared yesterday by Mounika (see civil-cp-tech-dev channel in Slack) so we actually have two approvals.

2023-04-07 11:00 UTC, merged