CIV-7994 Integrate with HMC API - Ticket 2
hmcts/civil-service pull request #2715
Opened 2023-05-15 14:36 UTC by adam-thomas-HMCTS

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-7994

### Change description ###

Model the PUT/partiesNotified element for HMC API integration 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-05-17 09:20 UTC, sherlynkhaw requested changes

2023-05-17 09:20 UTC, sherlynkhaw commented on commons-civil/src/main/java/uk/gov/hmcts/reform/hmc/client/HearingsApi.java
> +        @RequestParam("id") String id
not a problem but make sure you rebase before merging with master

it should be 
```@PathVariable("id") String id```

2023-05-17 09:20 UTC, sherlynkhaw commented on commons-civil/src/main/java/uk/gov/hmcts/reform/hmc/model/unnotifiedhearings/PartiesNotified.java
> +package uk.gov.hmcts.reform.hmc.model.unnotifiedhearings;
this model/file isn't used anywhere?

2023-05-17 12:18 UTC, adam-thomas-HMCTS commented on commons-civil/src/main/java/uk/gov/hmcts/reform/hmc/model/unnotifiedhearings/PartiesNotified.java
> +package uk.gov.hmcts.reform.hmc.model.unnotifiedhearings;
Removed

2023-05-17 12:49 UTC, Gareth40343 requested changes

2023-05-17 12:49 UTC, Gareth40343 commented on commons-civil/src/main/java/uk/gov/hmcts/reform/hmc/service/HearingsService.java
> +            return hearingNoticeApi.updatePartiesNotifiedRequest(
pass serviceData here too

2023-05-18 09:23 UTC, adam-thomas-HMCTS commented on commons-civil/src/main/java/uk/gov/hmcts/reform/hmc/service/HearingsService.java
> +    public ResponseEntity updatePartiesNotifiedResponse(String authToken, String hearingId, int requestVersion, LocalDateTime receivedDateTime) {
Changes made

2023-05-18 09:24 UTC, adam-thomas-HMCTS commented on commons-civil/src/main/java/uk/gov/hmcts/reform/hmc/client/HearingsApi.java
> +        @RequestHeader(AUTHORIZATION) String authorisation,
Changes made

2023-05-18 09:24 UTC, adam-thomas-HMCTS commented on commons-civil/src/main/java/uk/gov/hmcts/reform/hmc/service/HearingsService.java
> +            return hearingNoticeApi.updatePartiesNotifiedRequest(
changes made

2023-05-18 11:53 UTC, Gareth40343 approved these changes

2023-05-19 08:50 UTC, sankaviv1 submitted a review, later dismissed

2023-05-19 10:23 UTC, sherlynkhaw requested changes

2023-05-19 10:23 UTC, sherlynkhaw commented on commons-civil/src/main/java/uk/gov/hmcts/reform/hmc/model/unnotifiedhearings/PartiesNotified.java
> +    private Integer requestVersion;
you have request version in this and another in the api, it's duplicated?

2023-05-19 10:26 UTC, sherlynkhaw approved these changes

2023-06-12 15:03 UTC, douglasrice approved these changes

2023-06-12 15:03 UTC, merged