CIV-8067 initial commit
hmcts/civil-service pull request #2972
Opened 2023-07-17 08:37 UTC by bhagyashreesharma90

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-8067

### Change description ###
Added update template for Lip final order

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-07-18 07:45 UTC, LeonardoPalmeiro approved these changes

2023-07-26 11:03 UTC, kurt-uk requested changes

2023-07-26 11:03 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/GenerateOrderNotificationHandler.java
> +        if (taskId.equals("GenerateOrderNotifyApplicantSolicitor1")) {
use the static string TASK_ID_APP/RES

2023-07-27 08:49 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/GenerateOrderNotificationHandler.java
> +            || (isRespondent1Lip(caseData) && taskId.equals(TASK_ID_RESPONDENT1))
but the return here is just a lip template or a LR template, not a Lip applicant template, it doesnt seem to matter by your code if its a applicant or respondent, they both get the same template

2023-07-27 08:50 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/GenerateOrderNotificationHandler.java
> +            || (isRespondent1Lip(caseData) && taskId.equals(TASK_ID_RESPONDENT1))
what would the scenario it goes wrong be if you took that taskid check out?

2023-07-27 08:54 UTC, kurt-uk submitted a review, later dismissed

2023-07-27 08:59 UTC, LeonardoPalmeiro approved these changes

2023-08-04 08:15 UTC, LeonardoPalmeiro approved these changes

2023-08-04 08:24 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-08-04 08:35 UTC, hmcts-version1-ignacio approved these changes

2023-08-04 08:41 UTC, kurt-uk submitted a review, later dismissed

2023-08-07 08:35 UTC, LeonardoPalmeiro approved these changes

2023-08-07 08:58 UTC, maciejmodzelewski approved these changes

2023-08-14 14:21 UTC, LeonardoPalmeiro approved these changes

2023-08-14 14:24 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-08-16 06:58 UTC, hmcts-version1-ignacio approved these changes

2023-08-16 08:35 UTC, hmcts-version1-ignacio approved these changes

2023-08-16 08:41 UTC, m-meulendijks-v1 approved these changes

2023-08-17 10:25 UTC, kurt-uk approved these changes

2023-08-17 10:26 UTC, merged