CIV-7846 - Added Logic for Evidence Upload LiP notification
hmcts/civil-service pull request #3049
Opened 2023-07-26 14:04 UTC by m-meulendijks-v1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-7846

### Change description ###
Added a reference to the LiP template, and logic that allows an email to be sent to a LiP instead of an LR.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-26 15:09 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-27 10:42 UTC, miguelMolina3691 commented on commons-civil/src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
Shouldn't this be in civil-commons?

2023-07-27 10:46 UTC, miguelMolina3691 requested changes
NotificationsProperties.java is in civil-commons

2023-07-27 11:01 UTC, miguelMolina3691 submitted a review, later dismissed

2023-07-27 11:01 UTC, m-meulendijks-v1 commented on commons-civil/src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
It is, but it is also here from an earlier attempt, I think. Removed it now.

2023-07-27 11:10 UTC, LeonardoPalmeiro approved these changes

2023-08-16 08:07 UTC, hmcts-version1-ignacio commented on src/main/resources/application.yaml
> +
Extra blank line?

2023-08-16 09:35 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-08-16 09:37 UTC, maciejmodzelewski submitted a review, later dismissed

2023-08-16 10:07 UTC, maciejmodzelewski approved these changes

2023-08-16 10:08 UTC, LeonardoPalmeiro approved these changes

2023-08-16 10:35 UTC, kurt-uk approved these changes

2023-08-16 16:26 UTC, merged