CIV-10370 Add SDO claimant lip Notification
hmcts/civil-service pull request #3349
Opened 2023-10-06 10:57 UTC by miguelMolina3691

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-10370

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-10-06 11:14 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-10-06 12:57 UTC, LeonardoPalmeiro requested changes
please could you check the coverage ? some of the changes hasn't unit test.
https://sonarcloud.io/summary/new_code?id=civil-service&pullRequest=3349

2023-10-10 07:32 UTC, miguelMolina3691 commented
> please could you check the coverage ? some of the changes hasn't unit test. https://sonarcloud.io/summary/new_code?id=civil-service&pullRequest=3349

Updated with test

2023-10-10 08:06 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-10-10 08:07 UTC, m-meulendijks-v1 approved these changes

2023-11-13 10:34 UTC, LeonardoPalmeiro approved these changes

2023-11-17 09:42 UTC, laarmada approved these changes

2023-11-17 09:44 UTC, m-meulendijks-v1 approved these changes

2023-11-17 09:55 UTC, LeonardoPalmeiro approved these changes

2023-11-22 11:48 UTC, dharmendrak approved these changes

2023-11-22 17:56 UTC, merged