CIV-9024 Claimant Intent: Judgement by admission RPA
hmcts/civil-service pull request #3638
Opened 2023-11-27 14:36 UTC by kalachandrasekar1

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-9024

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-12-04 10:17 UTC, jarekPierchala requested changes

2023-12-04 10:32 UTC, kalachandrasekar1 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/ClaimantResponseCuiCallbackHandler.java
> +        } else if ((updatedData.hasApplicantRejectedRepaymentPlan()
fixed

2023-12-04 11:20 UTC, jarekPierchala approved these changes

2023-12-05 09:23 UTC, paul-pearson approved these changes

2023-12-12 14:19 UTC, merged