Civ 8903 dashboard settlement agreement
hmcts/civil-service pull request #3709
Opened 2023-12-08 13:46 UTC by paul-pearson

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-8903

### Change description ###

Implement new statuses for settlement agreement.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-12-08 16:06 UTC, ElifDenizEsea submitted a review, later dismissed

2023-12-12 08:54 UTC, portizdev requested changes

2023-12-12 08:54 UTC, portizdev commented on src/main/java/uk/gov/hmcts/reform/civil/model/citizenui/CcdDashboardDefendantClaimMatcher.java
> +    public boolean hasClaimantAndDefendantSignedSettlementAgreement() {
Move this to a common service instead of duplicating the same methods on 2 sites.

2023-12-12 10:48 UTC, portizdev submitted a review, later dismissed

2023-12-12 11:09 UTC, ElifDenizEsea approved these changes

2023-12-12 11:09 UTC, kenneth-hmcts submitted a review, later dismissed

2023-12-18 10:07 UTC, kenneth-hmcts approved these changes

2023-12-18 10:07 UTC, portizdev approved these changes

2023-12-18 10:08 UTC, rajakm approved these changes

2023-12-18 10:21 UTC, neeta-hmcts approved these changes

2023-12-18 10:22 UTC, merged