CIV-10054 More Information Required HWF
hmcts/civil-service pull request #4030
Opened 2024-02-12 18:18 UTC by kenneth-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-10054

### Change description ###
Set Up More Information Required HWF

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-02-13 17:14 UTC, ElifDenizEsea approved these changes

2024-02-14 09:15 UTC, manish14836 requested changes

2024-02-14 09:15 UTC, manish14836 commented on src/main/java/uk/gov/hmcts/reform/civil/enums/HwFMoreInfoRequiredDocuments.java
> +public enum HwFMoreInfoRequiredDocuments {
Suggestion:- can be sorted for more readability.

2024-02-14 09:15 UTC, manish14836 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/MoreInformationHwfCallbackHandler.java
> +            .put(callbackKey(MID, "more-information-hwf"), this::validationMoreInformation)
Move out of function and create a class variable and return class variable in callback method

2024-02-14 09:15 UTC, manish14836 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/MoreInformationHwfCallbackHandler.java
> +            FeeType.HEARING.equals(Optional.ofNullable(caseData.getHwfFeeType()).orElse(null))
Use == while comparing enums.  
FeeType.HEARING == caseData.getHwfFeeType()

2024-02-14 09:15 UTC, manish14836 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/MoreInformationHwfCallbackHandler.java
> +        System.out.println(hwFMoreInfoDocumentDate);
Remove this System.out.println(hwFMoreInfoDocumentDate);

2024-02-14 09:15 UTC, manish14836 commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/MoreInformationHwfCallbackHandlerTest.java
> +@SpringBootTest(classes = {
This test doesn't need Spring testcontext. 
Please check https://github.com/hmcts/civil-service/pull/4023

2024-02-14 09:15 UTC, manish14836 commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/MoreInformationHwfCallbackHandlerTest.java
> +    class AboutToStartCallback {
Not sure if class name is correct or not as your are writing test for mid event inside this. plz check

2024-02-14 09:15 UTC, manish14836 commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/MoreInformationHwfCallbackHandlerTest.java
> +                .build()
plz check if you need this build and builder, build 1 time in the end only

2024-02-14 17:08 UTC, manish14836 submitted a review, later dismissed

2024-02-15 08:38 UTC, portizdev commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/MoreInformationHwfCallbackHandlerTest.java
> +            CaseData caseData = CaseData.builder()
Use Given, When, Then pattern pls

2024-02-15 09:49 UTC, kenneth-hmcts commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/MoreInformationHwfCallbackHandlerTest.java
> +            CaseData caseData = CaseData.builder()
Update from review

2024-02-15 10:07 UTC, portizdev submitted a review, later dismissed

2024-02-15 10:21 UTC, manish14836 submitted a review, later dismissed

2024-02-15 13:57 UTC, manish14836 submitted a review, later dismissed

2024-02-18 17:19 UTC, merged