CIV-12752 RPA and Validations for judgments in HwF journey
hmcts/civil-service pull request #4077
Opened 2024-02-21 18:22 UTC by kenneth-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-12752

### Change description ###
Set up RPA for HwF

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-02-22 16:28 UTC, ElifDenizEsea approved these changes

2024-02-22 16:48 UTC, paul-pearson submitted a review, later dismissed

2024-02-26 11:53 UTC, neeta-hmcts approved these changes

2024-02-26 15:12 UTC, ElifDenizEsea requested changes

2024-02-26 15:12 UTC, ElifDenizEsea commented on src/test/java/uk/gov/hmcts/reform/civil/service/JudgementServiceTest.java
> +    JudgementService.class,
use mockito entension

2024-02-27 12:18 UTC, portizdev approved these changes

2024-02-27 15:46 UTC, ElifDenizEsea submitted a review, later dismissed

2024-02-27 15:48 UTC, manish14836 approved these changes

2024-02-28 11:23 UTC, ElifDenizEsea submitted a review, later dismissed

2024-02-28 11:36 UTC, sankhajuria submitted a review, later dismissed

2024-03-08 12:49 UTC, closed without merging