CIV-12693 dashboard notification fee paid
hmcts/civil-service pull request #4110
Opened 2024-02-27 15:21 UTC by GorilaNaranja

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-12693

### Change description ###
Dashboard Notification - When claim gets issued (Defendant)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-02-27 15:43 UTC, jarekPierchala requested changes

2024-02-27 15:43 UTC, jarekPierchala commented on src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/CreateDashboardScenarioTest.java
> +
why those empty lines?

2024-02-27 15:52 UTC, GorilaNaranja commented on src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/CreateDashboardScenarioTest.java
> +
fixed

2024-02-27 15:53 UTC, jarekPierchala approved these changes

2024-02-27 16:57 UTC, jarekPierchala approved these changes

2024-02-28 11:25 UTC, ElifDenizEsea approved these changes

2024-02-28 13:09 UTC, dharmendrak approved these changes

2024-03-01 10:06 UTC, merged