Update renovate config
hmcts/civil-service pull request #4283
Opened 2024-03-25 12:21 UTC by srochani

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-03-25 12:24 UTC, velimd submitted a review, later dismissed

2024-03-25 12:25 UTC, rishikrsharma approved these changes

2024-03-26 10:01 UTC, linusnorton requested changes
please update the schedule to 9am to 3pm

2024-03-26 10:04 UTC, linusnorton approved these changes

2024-03-26 10:21 UTC, jarekPierchala approved these changes

2024-03-26 10:51 UTC, mounikahmcts approved these changes

2024-03-26 11:02 UTC, merged