CIV-13074 Defendant dashboard - Claimant accepts court decision
hmcts/civil-service pull request #4294
Opened 2024-03-26 14:51 UTC by paul-pearson

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-13074

### Change description ###

Defendant dashboard - Claimant accepts court decision

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-03-26 15:49 UTC, laarmada requested changes

2024-03-26 16:45 UTC, paul-pearson commented on config/owasp/suppressions.xml
> +    <cve>CVE-2024-1597</cve>
First I tried updating org.postgresql to 42.6.1 to resolve this, which doesn't have the vulnerability according to https://nvd.nist.gov/vuln/detail/CVE-2024-1597.  That didn't work and looking at Jenkins logs it is complaining about postgresql-42.3.8.jar.  I then ran `./gradlew dependencies` to find that jar in the dependency tree, but it is not there.  So I was unable to resolve in any other way.  I then added it to suppressions.

2024-03-26 16:53 UTC, paul-pearson commented on config/owasp/suppressions.xml
> +    <cve>CVE-2024-1597</cve>
Ah ok, possibly the bump didn't work because I only updated one build.gradle file, not the other one.  Have now merged team2b branch so should be resolved hopefully.

2024-03-27 07:45 UTC, laarmada approved these changes

2024-03-28 16:56 UTC, dharmendrak approved these changes

2024-03-28 16:56 UTC, merged