CIV-13201 - Add Dashboard for Defendant Response Deadline Check
hmcts/civil-service pull request #4298
Opened 2024-03-26 16:19 UTC by m-meulendijks-v1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-13201

### Change description ###
When defendant does not respond in time, show this notification.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-03-27 13:14 UTC, jarekPierchala approved these changes

2024-03-27 14:41 UTC, paul-pearson requested changes

2024-03-27 14:41 UTC, paul-pearson commented on src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/claimant/DefendantResponseDeadlineScenarioTest.java
> +@Testcontainers
I don't think you need these two annotations here as they are inherited from the base class.

2024-03-27 14:41 UTC, paul-pearson commented on src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/dashboard/scenarios/claimant/DefendantResponseDeadlineScenarioTest.java
> +                    "<p class=\"govuk-body\">You can now request a county court judgement.<p/>" +
"judgement" here should be "judgment".

2024-03-27 14:41 UTC, paul-pearson commented on src/main/resources/db/migration/V2024_03_25_1606__CIV-13201_response_deadline_not_responded.sql
> +          '<p class="govuk-body">You can now request a county court judgement.<p/>'
"judgement" here should be "judgment".

2024-03-27 14:41 UTC, paul-pearson commented on src/main/resources/db/migration/V2024_03_25_1606__CIV-13201_response_deadline_not_responded.sql
> +          '<p class="govuk-body">You can now request a county court judgement.<p/>'
As above - should be "judgment".

2024-03-27 14:50 UTC, paul-pearson approved these changes

2024-03-28 14:48 UTC, dharmendrak approved these changes

2024-03-28 15:08 UTC, merged