CIV-11305 added notification
hmcts/civil-service pull request #4439
Opened 2024-04-09 08:39 UTC by laarmada

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-11306

### Change description ###

Upload documents (Defendant) 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-04-10 11:36 UTC, miguelMolina3691 submitted a review, later dismissed

2024-04-10 13:20 UTC, m-meulendijks-v1 approved these changes

2024-04-10 14:04 UTC, kannan-v-hmcts approved these changes

2024-04-11 10:36 UTC, dharmendrak submitted a review, later dismissed

2024-04-12 08:10 UTC, m-meulendijks-v1 requested changes

2024-04-12 08:10 UTC, m-meulendijks-v1 commented on src/main/resources/db/migration/V2024_04_05_0001__CIV-11305_upload_hearing_documents_claimant_scenario.sql
> +        'Notice.AAA6.CP.HearingDocuments.Upload.Claimant', 'Scenario.AAA6.CP.HearingDocuments.Upload.Claimant',
Please use the name of the Upload hearing documents fields (which I shared with you yesterday), you've given the name of the notice template, but these are different.
Please use **Hearing.Document.Upload**

2024-04-12 08:10 UTC, m-meulendijks-v1 commented on src/main/resources/db/migration/V2024_04_09_0001__CIV-11306_upload_hearing_documents_defendant_scenario.sql
> +        'Notice.AAA6.CP.HearingDocuments.Upload.Defendant', 'Scenario.AAA6.CP.HearingDocuments.Upload.Defendant',
Please use the name of the Upload hearing documents fields (which I shared with you yesterday), you've given the name of the notice template, but these are different.
Please use Hearing.Document.Upload

2024-04-12 09:11 UTC, m-meulendijks-v1 submitted a review, later dismissed

2024-04-25 11:59 UTC, m-meulendijks-v1 commented on src/main/resources/db/migration/V2024_04_05_0001__CIV-11305_upload_hearing_documents_claimant_scenario.sql
> +values ('<a href="{UPLOAD_HEARING_DOCUMENTS}">Upload hearing documents</a>', 'Hearings',
Was a decision made about whether a deadline should show here?
It's still mentioned in the ticket & don't see any comment that it is no longer relevant - but I don't see hintText added.

2024-04-25 12:02 UTC, miguelMolina3691 submitted a review, later dismissed

2024-04-25 12:36 UTC, kannan-v-hmcts submitted a review, later dismissed

2024-04-25 13:01 UTC, m-meulendijks-v1 submitted a review, later dismissed

2024-04-25 13:05 UTC, miguelMolina3691 submitted a review, later dismissed

2024-04-26 11:22 UTC, dharmendrak approved these changes

2024-04-26 12:19 UTC, merged