CIV-14215 - CUI Dashboard (old vs new)
hmcts/civil-service pull request #4947
Opened 2024-06-18 12:59 UTC by neeta-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-14215

### Change description ###
removed isDashboardServiceEnabled toggle

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-06-20 13:44 UTC, dharmendrak submitted a review, later dismissed

2024-06-21 08:20 UTC, kenneth-hmcts approved these changes

2024-06-21 08:27 UTC, laarmada requested changes
what about camunda and ccd removal flag?

2024-06-21 08:33 UTC, laarmada submitted a review, later dismissed

2024-06-21 09:54 UTC, laarmada submitted a review, later dismissed

2024-06-21 16:53 UTC, merged