feat/CIV-208 changed howMuchWasPaid to MoneyGBP
hmcts/civil-service pull request #535
Opened 2022-01-05 10:58 UTC by dtortolaV1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-208

### Change description ###
Change "how much was paid" from Number to MoneyGBP

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-01-05 13:41 UTC, bhssamray approved these changes

2022-01-05 13:44 UTC, bhssamray requested changes
Please consider the amount issue highlighted by Kenneth

2022-01-07 12:31 UTC, kenneth-hmcts commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimSpecCallbackHandler.java
> +            BigDecimal valuePounds = caseData.getRespondToAdmittedClaimOwingAmount().divide(
Is it possible to use function penniesToPounds in MonetaryConversions class in order to change from pennies to pounds?

2022-01-07 13:52 UTC, bhssamray approved these changes

2022-01-07 13:53 UTC, kenneth-hmcts approved these changes

2022-01-17 12:09 UTC, sampankumar commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimSpecCallbackHandler.java
> +                .compareTo(caseData.getTotalClaimAmount().multiply(BigDecimal.valueOf(100)));
Instead of multiplying by 100 could you please use MonetaryConversions class to convert pounds to pennies.

2022-01-19 12:06 UTC, kenneth-hmcts approved these changes

2022-01-19 12:10 UTC, indu2019 approved these changes
approved

2022-01-19 12:22 UTC, merged