CIV-15221 Changes To AHN Handler To Update The Hearing Fee Object
hmcts/civil-service pull request #5428
Opened 2024-09-13 13:34 UTC by kannan-v-hmcts

PR for https://tools.hmcts.net/jira/browse/CIV-15221

2024-09-17 09:43 UTC, HarryH96 requested changes

2024-09-17 09:43 UTC, HarryH96 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateHearingNoticeHmcHandler.java
> +                      .hearingFee(calculateAndApplyFee(hearingFeesService, caseData, claimTrack))
Can this be wrapped in a toggle for the CUI CP release please

2024-09-26 10:09 UTC, HarryH96 approved these changes

2024-09-26 11:20 UTC, miguelMolina3691 submitted a review, later dismissed

2024-10-07 14:49 UTC, dharmendrak approved these changes

2024-10-07 15:08 UTC, ss-evoco submitted a review, later dismissed

2024-10-08 08:59 UTC, miguelMolina3691 submitted a review, later dismissed

2024-10-09 12:02 UTC, m-meulendijks-v1 approved these changes

2024-10-09 12:44 UTC, merged