CIV-15258 fix bug
hmcts/civil-service pull request #5467
Opened 2024-09-20 11:41 UTC by miguelMolina3691

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-15258

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2024-09-25 08:34 UTC, ss-evoco requested changes

2024-09-25 08:34 UTC, ss-evoco commented on src/main/resources/db/migration/V2024_06_21_1155__CIV-14169-update-claimant-task-list-final-orders-issued.sql
>   * Add scenario
The production database scripts will have been run by the time the code freeze is lifted. All changes to previous scripts need to be done as update SQLs now.

2024-09-25 08:34 UTC, ss-evoco commented on src/main/resources/db/migration/V2024_06_21_1166__CIV-14169-update-defendant-task-list-final-orders-issued.sql
>   */
The production database scripts will have been run by the time the code freeze is lifted. All changes to previous scripts need to be done as update SQLs now.

2024-09-25 11:29 UTC, ss-evoco submitted a review, later dismissed

2024-09-25 11:39 UTC, kannan-v-hmcts commented
Hi @miguelMolina3691 The script you have added now will always update the Trial arrangements task list to Inactive when the order is issued. I see 2 issues here.

1. The task list will now appear and be shown as inactive for Small claims as well (Trial arrangements task list is not available for Small claims)
2. For a FT claim, the task list will be always updated to Inactive. I think we should only update it if the trial arrangements is not done. If its done already, we should leave it as Done 

I think we should split the scenario into 2 and update the task list accordingly. Please refer https://github.com/hmcts/civil-service/pull/5463

2024-09-25 13:20 UTC, dtortolaV1 approved these changes

2024-09-25 13:52 UTC, kannan-v-hmcts requested changes
Hi @miguelMolina3691 The script you have added now will always update the Trial arrangements task list to Inactive when the order is issued. I see 2 issues here.

The task list will now appear and be shown as inactive for Small claims as well (Trial arrangements task list is not available for Small claims)
For a FT claim, the task list will be always updated to Inactive. I think we should only update it if the trial arrangements is not done. If its done already, we should leave it as Done
I think we should split the scenario into 2 and update the task list accordingly. Please refer https://github.com/hmcts/civil-service/pull/5463

2024-09-27 11:45 UTC, kannan-v-hmcts approved these changes

2024-09-30 09:00 UTC, laarmada approved these changes

2024-09-30 09:01 UTC, ss-evoco requested changes

2024-09-30 10:14 UTC, miguelMolina3691 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/DashboardScenarios.java
> +    SCENARIO_AAA6_UPDATE_DASHBOARD_DEFENDANT_TASK_LIST_TRIAL_READY_FINAL_ORDERS("Scenario.AAA6.Update.Defendant.TaskList.TrialReady.FinalOrders"),
I have done it this way following the style of the scenario that would be executed if the conditions are not met, which would be this one
SCENARIO_AAA6_UPDATE_DASHBOARD_DEFENDANT_TASK_LIST_UPLOAD_DOCUMENTS_FINAL_ORDERS(‘Scenario.AAA6.Update.Defendant.TaskList.UploadDocuments.FinalOrders’)

What could be a more accurate name? @ss-evoco

2024-10-03 08:43 UTC, kannan-v-hmcts submitted a review, later dismissed

2024-10-03 09:29 UTC, ss-evoco submitted a review, later dismissed

2024-10-15 15:16 UTC, ss-evoco approved these changes

2024-10-15 15:19 UTC, kannan-v-hmcts approved these changes

2024-10-16 07:22 UTC, merged