CIV-15312 removing previous hwf notifications
hmcts/civil-service pull request #5498
Opened 2024-09-27 09:36 UTC by laarmada

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-15312
https://tools.hmcts.net/jira/browse/CIV-15315

### Change description ###

removing previous hwf notifications

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-09-27 10:11 UTC, ss-evoco approved these changes

2024-09-27 10:13 UTC, kannan-v-hmcts requested changes
Is this PR for both https://tools.hmcts.net/jira/browse/CIV-15312
https://tools.hmcts.net/jira/browse/CIV-15315 ?

2024-09-27 10:20 UTC, kannan-v-hmcts requested changes
The Claim fee and the hearing fee notices are mixed up in the updates ? Isn't ticket only for hearing fee HwF ?

2024-09-27 11:09 UTC, kannan-v-hmcts approved these changes

2024-09-27 11:41 UTC, miguelMolina3691 approved these changes

2024-09-30 16:09 UTC, dharmendrak approved these changes

2024-09-30 16:09 UTC, merged