DTSCCI-923 Concurrency violations refactoring
hmcts/civil-service pull request #5534
Opened 2024-10-01 13:26 UTC by guygrewal77

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/DTSCCI-923

Change description
Refactored various components to address concurrency vulnerability

Testing branch and instruction
Does this PR introduce a breaking change? (check one with "x")

[ ] Yes
[ ] No

2024-10-01 13:45 UTC, velimd approved these changes

2024-10-03 08:31 UTC, gmikerlemos requested changes
There is no need to call externalTaskService.complete(externalTask) you can have a single call with both arguments and if variableMap is null, the implementation code is ready to handle it as this is just a series of overloaded methods with different arguments where the base method has all arguments.


EDIT: In addition to this required changes which are unrelated to the concurrency issue, I must note that I would prefer said issue to be handled by defining scopes to the beans rather than passing the variable as a return argument to the method however I hope this route has already been attempted and failed for some reason.

2024-10-07 13:51 UTC, guygrewal77 commented on src/main/java/uk/gov/hmcts/reform/civil/callback/CallbackHandler.java
> -    private static final Logger LOG = LoggerFactory.getLogger(CallbackHandler.class);
Resolved

2024-10-07 13:55 UTC, guygrewal77 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/BaseExternalTaskHandler.java
> +            ofNullable(getVariableMap(data)).ifPresentOrElse(
Resolved

2024-10-08 12:22 UTC, gmikerlemos approved these changes

2024-10-08 14:22 UTC, ed14537 approved these changes

2024-10-15 09:04 UTC, merged