CMC-1885: Inform agreed extension date - 1v2 diff sols
hmcts/civil-service pull request #556
Opened 2022-01-13 22:40 UTC by jeejavr

https://tools.hmcts.net/jira/browse/CMC-1885

Added code to validate extension date entered by second defendant solicitor in 1v2 scenario
Added code to restrict users from accessing the event again
Code updation to reflect the extended date of respondent 2 on the confirmation page
Test cases updation

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-01-14 21:47 UTC, akriti-hmcts reviewed
There are failing tests on this PR. @jeejavr Please fix those

2022-01-15 21:11 UTC, akriti-hmcts reviewed
There is no unit test added for the scenario on InformAgreedExtensionDateCallbackHandler

2022-01-16 17:55 UTC, akriti-hmcts requested changes

2022-01-16 17:55 UTC, akriti-hmcts commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InformAgreedExtensionDateCallbackHandlerTest.java
> +                .containsOnly("This action cannot currently be performed because it has already been completed");
Can this String be defined as a final variable please

2022-01-17 09:07 UTC, akriti-hmcts approved these changes

2022-01-20 00:40 UTC, HarryH96 commented on src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapper.java
> +
Test cases will need to be added for this file.
In relation to the `dateReceived` field in this method, it is currently specific to respondent 1 only.. What if respondent2 is asking for a time extension, is this date being stored somewhere?

2022-01-22 10:29 UTC, akriti-hmcts approved these changes

2022-01-22 17:32 UTC, mounikahmcts approved these changes

2022-01-22 18:35 UTC, douglasrice approved these changes

2022-01-22 18:36 UTC, merged