DTSCCI-903 Consolidate work arounds that re-establish Case Flags on case data for LR events
hmcts/civil-service pull request #5662
Opened 2024-10-17 14:58 UTC by tiagreaney

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-10-18 08:09 UTC, ruban72 commented on src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/AcknowledgeClaimCallbackHandlerTest.java
> +            //assertThat(response.getData()).doesNotContainKey("respondent1Copy");
Can we remove this commented out code if not required?

2024-10-22 12:21 UTC, ruban72 requested changes
Looks like there is compile issue:
https://github.com/hmcts/civil-service/actions/runs/11443682812/job/31836878123?pr=5662

2024-10-23 10:29 UTC, gmikerlemos commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/AcknowledgeClaimCallbackHandler.java
> +        var caseDateBuilder = caseData.toBuilder();
Can you not do it as a one liner? caseData.toBuilder().solicitorReferencesCopy(etc).etc().build()

2024-10-23 10:36 UTC, gmikerlemos submitted a review, later dismissed

2024-10-23 10:36 UTC, gmikerlemos commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/AcknowledgeClaimCallbackHandler.java
>          } else if (caseData.getAddRespondent2() != null && caseData.getAddRespondent2().equals(YES)
Could use the opportunity to refactor a bit like this conditional could be extracted to a method for better readability

2024-10-23 11:39 UTC, gmikerlemos approved these changes

2024-11-13 11:58 UTC, velimd commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimSpecCallbackHandler.java
> +                    PersistDataUtils.persistFlagsForParties(caseData, oldCaseData, caseDataBuilder);
shouldnt this be persistPartyAddress()?

2024-11-13 11:58 UTC, velimd commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimSpecCallbackHandler.java
> -                updatedData.respondent2DetailsForClaimDetailsTab(updatedRespondent2.toBuilder().flags(null).build());
I feel like this persistFlagsForParties method should be here no due to the case flag issue?

2024-11-13 11:58 UTC, velimd commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToClaimCallbackHandler.java
> +                PersistDataUtils.persistPartyAddress(oldCaseData, caseData);
What about the respondent2DetailsForClaimDetailsTab? this part doesnt consider it right?

2024-11-26 11:43 UTC, closed without merging