DTSCCI-685
hmcts/civil-service pull request #5756
Opened 2024-10-31 16:49 UTC by AbuSalamHMCTS

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2025-07-28 15:50 UTC, anirudha-deshpande approved these changes

2025-07-30 08:08 UTC, nigeldunne submitted a review, later dismissed

2025-09-22 12:49 UTC, nigeldunne approved these changes

2025-09-22 13:01 UTC, ruban72 requested changes
Changes look good but I think would be better if we pass in CaseData and anything else that is required in the methods rather than CallBackParams

2025-09-22 13:15 UTC, ruban72 approved these changes

2025-09-22 13:21 UTC, merged