CIV-15640 add about to submit for court officer
hmcts/civil-service pull request #5843
Opened 2024-11-26 11:01 UTC by laarmada

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-15640

### Change description ###

Court officer order - Send LR and LiP email notifications

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-11-28 10:53 UTC, miguelMolina3691 requested changes
Could you add a unit test test for about-to-submit method? not that it's necessary, but in order not to lower code coverage

2024-11-28 15:21 UTC, m-meulendijks-v1 commented on src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CourtOfficerOrderHandler.java
> +
Should this be behind a feature toggle? Otherwise It will go straight into production

2024-12-02 09:13 UTC, m-meulendijks-v1 approved these changes

2024-12-03 08:42 UTC, miguelMolina3691 submitted a review, later dismissed

2024-12-03 09:09 UTC, m-meulendijks-v1 approved these changes

2024-12-25 03:03 UTC, closed without merging