Feat/cmc 1679
hmcts/civil-service pull request #700
Opened 2022-02-23 13:10 UTC by bhssamray

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CMC-1679

### Change description ###
This ticket is for changes pertaining to CLAIM_DETAILS_NOTIFIED_TIME_EXTENSION flow event for RPA event

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-02-25 12:34 UTC, Gareth40343 submitted a review, later dismissed

2022-02-28 11:24 UTC, sankaviv1 approved these changes

2022-03-01 12:39 UTC, douglasrice requested changes

2022-03-03 13:56 UTC, Gareth40343 approved these changes

2022-03-03 16:56 UTC, HarryH96 approved these changes

2022-03-08 21:45 UTC, akriti-hmcts requested changes

2022-03-08 21:45 UTC, akriti-hmcts commented on src/main/java/uk/gov/hmcts/reform/civil/service/robotics/mapper/EventHistoryMapper.java
> +        if (scenario == ONE_V_TWO_TWO_LEGAL_REP && defendant2ExtensionExists.test(caseData)) {
this logic here will never be evaluated we may have to think about it and revise this code

2022-03-29 09:23 UTC, closed without merging